### ISSUE TITLE
При попытке генерации SiteMap получаю ошибку.

### ISSUE THREAD

**Issue by vladkrutov** [axis/axiscommerce#209]
При попытке генерации SiteMap получаю ошибку.

```
Notice: Undefined index:  2  in /home/data/www/app/code/Axis/Sitemap/controllers/Admin/FileController.php on line 216<br />
#0 /home/data/www/app/code/Axis/Sitemap/controllers/Admin/FileController.php(216): AxisErrorHandler(8, 'Undefined index...', '/home/flashdres...', 216, Array)<br />
#1 /home/data/www/library/Zend/Controller/Action.php(516): Axis_Sitemap_Admin_FileController->createAction()<br />
#2 /home/data/www/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('createAction')<br />
#3 /home/data/www/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))<br />
#4 /home/data/www/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()<br />
#5 /home/data/www/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()<br />
#6 /home/data/www/index.php(73): Zend_Application->run()<br />
#7 {main}
```

**Comment by vladkrutov** [comment]
Не смог повторить на чистой инсталляции.
Видимо ошибка порождена теми же причинами, что и #210
Прошу помощи.

**Comment by vovayatsyuk** [comment]
Скорее всего причина в использовании тестовой базы данных.

app/code/Axis/Sitemap/controllers/Admin/FileController.php.

изменить строки ~207-208

```
        foreach($pages as $_page) {
            $title = empty($_page['title']) ? $_page['link'] : $_page['title'];
```

на

```
        foreach($pages as $_page) {
            // sample database could add content for non-existing language
            if (!isset($locales[$_page['language_id']])) {
                continue;
            }
            $title = empty($_page['title']) ? $_page['link'] : $_page['title'];
```

**Comment by vladkrutov** [comment]
О чудо! Всё теперь работает!
