### ISSUE TITLE
перестали приниматься заказы.

### ISSUE THREAD

**Issue by vladkrutov** [axis/axiscommerce#210]
Удалил ненужные страны и теперь после сабмита заказа выскакивает ошибка.

```
2012-07-13T15:06:54+04:00 DEBUG (7): Notice: Undefined index:    in /home/samplesite.ru/data/www/samplesite.ru/app/code/Axis/Core/Model/Site.php on line 130
#0 /home/samplesite.ru/data/www/samplesite.ru/app/code/Axis/Core/Model/Site.php(130): AxisErrorHandler(8, 'Undefined index...', '/home/flashdres...', 130, Array)
#1 /home/samplesite.ru/data/www/samplesite.ru/library/Axis/Mail.php(65): Axis_Core_Model_Site->getCompanyInfo()
#2 /home/samplesite.ru/data/www/samplesite.ru/app/code/Axis/Sales/Model/Observer.php(46): Axis_Mail->__construct()
#3 /home/samplesite.ru/data/www/samplesite.ru/library/Axis/Event/Observer.php(97): Axis_Sales_Model_Observer->notifyAdminNewOrder(Object(Axis_Sales_Model_Order_Row))
#4 /home/samplesite.ru/data/www/samplesite.ru/library/Axis.php(271): Axis_Event_Observer->dispatch('sales_order_cre...', Object(Axis_Sales_Model_Order_Row))
#5 /home/samplesite.ru/data/www/samplesite.ru/app/code/Axis/Checkout/controllers/IndexController.php(75): Axis::dispatch('sales_order_cre...', Object(Axis_Sales_Model_Order_Row))
#6 /home/samplesite.ru/data/www/samplesite.ru/library/Zend/Controller/Action.php(516): Axis_Checkout_IndexController->successAction()
#7 /home/samplesite.ru/data/www/samplesite.ru/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('successAction')
#8 /home/samplesite.ru/data/www/samplesite.ru/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /home/samplesite.ru/data/www/samplesite.ru/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /home/samplesite.ru/data/www/samplesite.ru/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /home/samplesite.ru/data/www/samplesite.ru/index.php(73): Zend_Application->run()
#12 {main}
```

**Comment by vladkrutov** [comment]
Пользователю выдаётся сообщение об ошибке, но заказ в админке регистрируется правильно.

**Comment by vladkrutov** [comment]
Не смог повторить на чистой инсталляции.
Видимо ошибка порождена теми же причинами, что и #209
Прошу помощи.

**Comment by vovayatsyuk** [comment]
Страны удалять не нужно. Для скрытия есть конфиг опция account/address_form/country_id_allow.

Раз уж удалили, то нужно изменить настройки, которые используют страну:
- core/company/country
- account/address_form/country_id_value
- core/store/country

p.s. Наверное уберем возможность удаления страны из базы. Меньше проблем будет :)

**Comment by vladkrutov** [comment]
Прописал все страны и зоны и, о чудо, всё заработало.
Спасибо большое!
