### ISSUE TITLE
Saving cms page layout from grid (batch save)

### ISSUE THREAD

**Issue by vovayatsyuk** [axis/axiscommerce#63]
When the layout is selected from dropdown (example: layout_2columns-right (default)) and page is saved, I recieve the following message on the frontend for this page:

```
script 'layout_2columns-right (default).phtml' not found in path (D:/www/htdocs/axis.com/app/code/Axis/Cms/views\scripts/;D:/www/htdocs/axis.com/app/design/front/fallback/templates/cms/;D:/www/htdocs/axis.com/app/design/front/fallback/templates/;D:/www/htdocs/axis.com/app/design/front/default/layouts/;D:/www/htdocs/axis.com/app/design/front/default/templates/cms/;D:/www/htdocs/axis.com/app/design/front/default/templates/)
Trace:
#0 D:\www\htdocs\axis.com\library\Zend\View\Abstract.php(884): Zend_View_Abstract->_script('layout_2columns...')
#1 D:\www\htdocs\axis.com\library\Axis\Layout.php(173): Zend_View_Abstract->render('layout_2columns...')
#2 D:\www\htdocs\axis.com\library\Axis\Controller\Plugin\Layout.php(300): Axis_Layout->render()
#3 D:\www\htdocs\axis.com\library\Zend\Controller\Plugin\Broker.php(331): Axis_Controller_Plugin_Layout->postDispatch(Object(Zend_Controller_Request_Http))
#4 D:\www\htdocs\axis.com\library\Zend\Controller\Front.php(965): Zend_Controller_Plugin_Broker->postDispatch(Object(Zend_Controller_Request_Http))
#5 D:\www\htdocs\axis.com\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#6 D:\www\htdocs\axis.com\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#7 D:\www\htdocs\axis.com\index.php(75): Zend_Application->run()
#8 {main}
```

**Comment by vovayatsyuk** [comment]
https://github.com/axis/axiscommerce/commit/02bed1c44c55bee73d013ad88b7e0d3216a12e98
