### ISSUE TITLE
Warning: htmlspecialchars()

### ISSUE THREAD

**Issue by ghost** [axis/axiscommerce#67]
admin/configuration have some issue.

try to change "payment/paypal_standard/email","mail/smtp/user""mail/smtp/password" have this issue.

try to change"mail/smtp/host" do not this issue.

2011-07-08T20:50:24+06:00 DEBUG (7): Warning: htmlspecialchars() [<a href='function.htmlspecialchars'>function.htmlspecialchars</a>]: Invalid multibyte sequence in argument  in /library/Zend/View/Abstract.php on line 905
#0 [internal function]: AxisErrorHandler(2, 'htmlspecialchar...', '/pub...', 905, Array)
#1 /library/Zend/View/Abstract.php(905): htmlspecialchars('??;B????', 2, 'UTF-8')
#2 /library/Zend/View/Helper/FormText.php(77): Zend_View_Abstract->escape('htmlspecialchar...', '??;B????', 2, 'UTF-8')
#3 /library/Zend/View/Abstract.php(350): Zend_View_Helper_FormText->formText('??;B????')
#4 [internal function]: Zend_View_Abstract->__call('confValue', '??;B????', Array)
#5 /library/Axis/Config/Handler/Crypt.php(60): Zend_View->formText(Array, Array)
#6 /app/code/Axis/Admin/controllers/ConfigurationController.php(73): Axis_Config_Handler_Crypt::getHtml('formText', Array)
#7 /app/code/Axis/Admin/controllers/ConfigurationController.php(221): Axis_Admin_ConfigurationController->_getHtml('confValue', '??;B????', Array)
#8 /library/Zend/Controller/Action.php(513): Axis_Admin_ConfigurationController->editAction('gpZhxrjtkNo=', Object(Zend_View))
#9 /library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch(Array, 'gpZhxrjtkNo=', Object(Zend_View))
#10 /library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch('Crypt', 'gpZhxrjtkNo=')
#11 /library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run('editAction')
#13 /index.php(75): Zend_Application->run(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#14 {main}

**Comment by ghost** [comment]
version 0.8

**Comment by ghost** [comment]
it was an temp issue. fresh install no issue.
